### ISSUE TITLE
Cannot record in QuickTime Player

### ISSUE THREAD

**Issue by iKenndac** [johnboiles/coremediaio-dal-minimal-example#10]
Thank you for making this really great example. It's by far the most understandable one I've found!

When you click "Record" in QuickTime Player, you immediately get the error "Recording Stopped". You do get a movie of two frames, though.

Do you know why this might be happening? 

<img width="1392" alt="Screenshot 2020-05-03 at 12 38 31" src="https://user-images.githubusercontent.com/514900/80912109-071ab880-8d3b-11ea-83db-b8960b740607.png">

**Comment by johnboiles** [comment]
Thanks for the report and great catch. I bet it's a time stamping issue and probably the same as https://github.com/seanchas116/SimpleDALPlugin/issues/2 (that project is a Swift port of this one). If you're able to figure it out please post a PR!

**Comment by johnboiles** [comment]
Fixed in #11. Thanks @iKenndac!
