### ISSUE TITLE
Can't find the Virtual Camera

### ISSUE THREAD

**Issue by jimmyjeng** [johnboiles/coremediaio-dal-minimal-example#15]
Hi, thank you for this example.

After i build this example and put plug-in in "/Library/CoreMediaIO/Plug-Ins/DAL" folder.

I can see a new virtual camera show up at QuickTime Player and OBS.

But i can't find the same virtual camera when i using like zoom, Teams, google meet.

Is there anything i need to do? thank you.

**Comment by johnboiles** [comment]
Zoom only supports some very specific virtual cameras. See [here](https://github.com/johnboiles/obs-mac-virtualcam/issues/4#issuecomment-638220117) for the list someone dumped from the Zoom binary. See also [here](https://github.com/johnboiles/obs-mac-virtualcam/wiki/Compatibility) where we're collecting a list of apps that have disabled virtual cameras.
