### ISSUE TITLE
Sometimes crashes the host app

### ISSUE THREAD

**Issue by johnboiles** [johnboiles/coremediaio-dal-minimal-example#2]
This is probably a bug in my CF memory management. Or it could be that I need to add locks / mutexes somewhere. The stack trace doesn't show the apps crashing inside my code however so I think it's most likely memory management.

**Comment by johnboiles** [comment]
So there was this impossible undocumented quirk where you need to retain the clock every time you return it (but not other memory managed objects). I wish Apple would just tell you this kind of thing in their docs.

https://github.com/johnboiles/coremediaio-dal-minimal-example/commit/00fd8e0395a0d587758467790671fdd1130864d7#diff-73bc21c261ed88b265c8bcdb4bed9dccR294

But it's fixed now :tada:

**Comment by gxalpha** [comment]
> So there was this impossible undocumented quirk where you...

I like how you speak about "this one" undocumented quirk. This whole thing is an undocumented mess :D
