### ISSUE TITLE
How to send windowID from a application to this DAL plugin for window capturing?

### ISSUE THREAD

**Issue by alokmahor** [johnboiles/coremediaio-dal-minimal-example#27]
Currently this DAL plugin output moving square. I want to output any specific window capture so I want to send windowID from a application. I need to use IPC(Inter Process Communication) to pass windowID to DAL plugin.

But I am not sure which IPC approach should I use for such one way communication from application to DAL plugin.

**Comment by johnboiles** [comment]
You can use the deprecated distributed objects ipc method (this is what OBS does). This can work directly from the host application to the DAL plugin.

Or you can use XPC, but for XPC you'll need a LaunchAgent that passes messages between the two processes.

I've used both. XPC is not deprecated so probably the best for new projects.
