### ISSUE TITLE
MacOS development how to use the plug-in to connect camera data

### ISSUE THREAD

**Issue by bird1423** [johnboiles/coremediaio-dal-minimal-example#28]
hi,johnboiles:
    We plan to develop an AI video conference system, which requires a virtual camera. After reading your code, I still don't understand how to call this plug-in in the development of MacOS. For example, how can I process the video collected data through AI, associate the data with the virtual camera head, and let software such as zoom connect directly to my virtual camera, I hope you can make a demo for simple use of MacOS, and look forward to your reply，thank you!

**Comment by johnboiles** [comment]
This is an overly broad question. Do some more reading and feel free to hit me up when you have more specific questions.
