### ISSUE TITLE
Stops other cameras from working

### ISSUE THREAD

**Issue by gxalpha** [johnboiles/coremediaio-dal-minimal-example#4]
When the plugin is in the correct folder, together with the obs-mac-virtualcam dal-plugin, the latter doesn't work anymore. While I can still select it (in Jitsi in my case), there is no signal coming through, Jitsi says it's unable to access the camera. 
In QuickTime I'm not able to test it due to https://github.com/johnboiles/coremediaio-dal-minimal-example/issues/2, which makes me think it might have something to do with it. QuickTime always crashes for me, maybe Chrome has a better failsafe built in.

**Comment by johnboiles** [comment]
Oh it stops all other DAL plugins from working? This is a great datapoint; I didn't test this. Thank you!

I agree seems likely to be the same root cause as #2

**Comment by johnboiles** [comment]
I think i've fixed it now! @gxalpha can you give it a try?

**Comment by gxalpha** [comment]
Can verify that it works! It shows the hi.png picture and doesn't interfere with other cameras. 
Works with Discord as well, thus trying to fix https://github.com/johnboiles/obs-mac-virtualcam/issues/37 won't be necessary.

**Comment by johnboiles** [comment]
Yay!!!
