### ISSUE TITLE
CMIOMinimalSample.plugin not appearing after build

### ISSUE THREAD

**Issue by ichiroyamato** [johnboiles/coremediaio-dal-minimal-example#5]
hi sir, thank you for developing this plugin.

Since I wanted to try your plugin, I cloned the repository and ran the build on Xcode under the following environment as mentioned on the readme file:
```
macOS Catalina(Version 10.15.4)
Xcode(Version 11.4.1)
```
I have also changed my codesigning on my personal developer identity, but the CMIOMinimalSapmle.plugin does not seem to appear on my mac.
Is there any additional settings/requirements, to try this plugin?

**Comment by gxalpha** [comment]
Hey, does it say "built successfully"?

If yes, if you check under "Products", does it appear there?

**Comment by ichiroyamato** [comment]
@gxalpha thank you so much! I found it(I misunderstood where to search for). This COVID phenomena is very depressing, but if in the future, you have chance to visit Tokyo,Japan please contact me and I will take you to the best places.

**Comment by johnboiles** [comment]
@ichiroyamato thank you for trying this! Were you able to confirm the source shows up successfully for you in any apps?

**Comment by ichiroyamato** [comment]
@johnboiles hi sir, I heavily appreciate your effort and kindness in running this project, and I have been able to confirm your source showing up in google hangouts(in Chrome browser) shown below like Snap Camera. This is fantastic(I have been trying to do this, googling the internet for more than 2 weeks). 

However, after firing up Quicktime, console.app, and google hangouts (in Chrome browser), the log prefixed "CMIOMS" does not seem to appear in the console.app. Do you have any ideas? I will post a screenshot below, so it might make the point easier to understand. 

And also, if COVID gets over, and we can be able travel around the world as we used to, and you have chance to visit Tokyo, please contact me so I can take you to the best places.

**Comment by ichiroyamato** [comment]
<img width="738" alt="Screen Shot 2020-04-24 at 21 22 10" src="https://user-images.githubusercontent.com/16098628/80212536-9f95a680-8672-11ea-801a-3e5c67195347.png">

**Comment by gxalpha** [comment]
Hi @ichiroyamato,

console.app only shows logs that have been written when it while open. Did you already have it open when you started hangouts? If not, then this is probably the reason.

**Comment by ichiroyamato** [comment]
@gxalpha hi sir, it appeared!!! Thank you for your advice! It also showed the hi.png in hangouts!

**Comment by ichiroyamato** [comment]
<img width="736" alt="Screen Shot 2020-04-24 at 21 38 22" src="https://user-images.githubusercontent.com/16098628/80213376-0798bc80-8674-11ea-9ccb-74e6998eff92.png">
